services:
  server:
    image: hentioe/capinde:0.1.0
    restart: always
    environment:
      CAPINDE_HOST: 0.0.0.0
      CAPINDE_WORKING_MODE: hosted # <- 默认工作在 hosted 模式，可修改为 `localized`
      CAPINDE_API_KEY: ${CAPINDE_API_KEY} # <- 使用 `openssl rand -base64 48` 生成
    volumes:
      - ./albums:/home/capinde/albums # <- 将图集持久化到宿主机
      - ./uploaded:/home/capinde/uploaded # <- 将已上传的资源持久化到宿主机
      - ./namespace:/home/capinde/namespace # <- 将命名空间内的输出文件持久化到宿主机
    healthcheck:
      test: ["CMD", "capinde", "--healthcheck"]
      start_period: 3s
      interval: 60s
      timeout: 1s
      retries: 3
